set -g default-terminal "screen-256color"
# set -g mode-keys vi

unbind r
bind r source-file ~/.tmux.conf 

bind '"' split-window -v -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'

bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r h select-pane -L

bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r H resize-pane -L 5

bind -r m resize-pane -Z 5

set -g mouse on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

set -g status on
set -g status-interval 2


#tpm plugin
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'seebi/tmux-colors-solarized'

set -g @colors-solarized 'dark'

set -g @plugin 'jimeh/tmux-themepack'

set -g @themepack 'powerline/default/cyan'

run '~/.tmux/plugins/tpm/tpm'
